# Form implementation generated from reading ui file 'showprizes.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(834, 591)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(380, 500, 291, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(28)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Ignore | QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.contentbox = QtWidgets.QLabel(parent=Dialog)
        self.contentbox.setGeometry(QtCore.QRect(0, 0, 871, 481))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(24)
        self.contentbox.setFont(font)
        self.contentbox.setObjectName("contentbox")
        self.comboBox = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox.setGeometry(QtCore.QRect(0, 500, 371, 61))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(28)
        self.comboBox.setFont(font)
        self.comboBox.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.contentbox.setText(_translate("Dialog", "TextLabel"))
        self.comboBox.setItemText(0, _translate("Dialog", "Not selected"))